#!/bin/bash

# Installs this configuration in the current user's linux machine.

DIR=$(pwd)

git submodule update --init

cd ..
ln -i -s $DIR/zshrc $HOME/.zshrc
ln -i -s $DIR/.gitconfig $HOME/.gitconfig
ln -i -s $DIR/.tmux.conf $HOME/.tmux.conf
