#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Setup packages
echo 'Installing packages...'
brew update
brew install ack
brew install atool
brew install binutils
brew install cabal-install
brew install cctools
brew install cmake
brew install coreutils
brew install ctags
brew install d-bus
brew install gettext
brew install ghc
brew install gnutls
brew install htop-osx
brew install imagemagick
brew install jpeg
brew install macvim
brew install node
brew install openssl
brew install pcre
brew install pkg-config
brew install prettyping
brew install protobuf
brew install readline
brew install sqlite
brew install the_silver_searcher
brew install tig
brew install tmux
brew install vim
brew install wget
brew install xz

brew install caskroom/cask/brew-cask

# Link
brew linkapps

# Install Haskell packages
cabal update
cabal install happy
cabal install ghc-mod
cabal install hdevtools
