#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true

# Setup packages
brew update
echo 'Installing packages...'

brew install ack
brew install atool
brew install binutils
brew install cabal-install
brew install cctools
brew install cmake
brew install coreutils
brew install ctags
brew install curl
brew install dos2unix
brew install entr
brew install ghc
brew install gist
brew install git
brew install imagemagick
brew install jpeg
brew install macvim
brew install maven
brew install multitail
brew install node
brew install openssl
brew install prettyping
brew install q
brew install readline
brew install rlwrap
brew install speedtest-cli
brew install sqlite
brew install the_silver_searcher
brew install tig
brew install tmux
brew install vim
brew install wget

brew install caskroom/cask/brew-cask

# Link
brew linkapps

# Install Haskell packages
cabal update
cabal install happy
cabal install hdevtools

git clone https://github.com/kazu-yamamoto/ghc-mod /tmp/ghc-mod
cabal install /tmp/ghc-mod
