#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Setup packages
brew update
echo 'Installing packages...'

brew install ack
brew install atool
brew install binutils
brew install cabal-install
brew install cctools
brew install chktex
brew install cmake
brew install coreutils
brew install ctags
brew install curl
brew install d-bus
brew install dos2unix
brew install gettext
brew install ghc
brew install gist
brew install git
brew install gnutls
brew install htop-osx
brew install imagemagick
brew install jpeg
brew install macvim
brew install maven
brew install mercurial
brew install multitail
brew install node
brew install openssl
brew install pcre
brew install pkg-config
brew install prettyping
brew install protobuf
brew install python
brew install python3
brew install q
brew install readline
brew install rlwrap
brew install smlnj
brew install sqlite
brew install sshfs
brew install the_silver_searcher
brew install tig
brew install tmux
brew install vim
brew install wget
brew install wget
brew install xz

brew install caskroom/cask/brew-cask

# Link
brew linkapps

# Install Haskell packages
cabal update
cabal install happy
cabal install ghc-mod
cabal install hdevtools
